spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/fundmatch
    username: postgres
    password: latifa
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  main:
    allow-circular-references: true

server:
  port: 9091

mail:
  host: smtp.gmail.com
  port: 587
  username: chakirlatifa2001@gmail.com
  password: pleg lcgg coss bhub
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
zoom:
  client-id: hYUeFx46SjWSlxAPDugYQ
  client-secret: g4KvK32MkGcvAWK4NEqUMDz0Xn1slwMf
  account-id: FC8LKKWtRymbZCOoxTdywQ
